name: Build

on:
  push:
    branches: 
      - master
  workflow_dispatch:
    inputs:
      use_nuitka_develop_version:
        description: 'use Nuitka develop version / 使用Nuitka 开发版编译.'
        required: true
        default: 'false'

env:
  UPLOAD_TO_ACTIONS: ${{ true }}
  PYTHON_VERSION: ${{ '3.10.2' }}
  PYTHON_ARCHITECTURE: ${{ 'x64' }}
  RELEASES_NAME_PERFIX: ${{ 'Claset-Build' }}
  CACHE_NUITKA_GCC: ${{ true }}
  CACHE_PYPI: ${{ true }}
  CACHE_BUILD: ${{ true }}
  RETENTION_DAYS: ${{ 16 }}
  DEFAULT_MODULE_NAME: ${{ 'CommandLine' }}

jobs:
  Build_Translations:
    name: Build_Translations
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2


  Build_Windows:
    name: Build_Windows
    runs-on: windows-latest
    needs: Build_Translations
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Generate Times
        id: genReleaseTimes
        run: |
          echo "::set-output name=tag::$(date +'%Y/%m/%d_%H/%M/%S')"
          echo "::set-output name=filename::$(date +'%Y-%m-%d_%H-%M-%S')"


      - name: Generate release name
        id: genFileName
        run: |
          echo "::set-output name=filename::${{ env.RELEASES_NAME_PERFIX }}-${{ runner.os }}-${{ env.PYTHON_ARCHITECTURE }}-${{ steps.genReleaseTimes.outputs.filename }}.exe"


      - name: PyPI Cache
        if: ${{ env.CACHE_PYPI }}
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-cache-python-pip-${{ hashFiles('**/requirements_build.txt') }}
          restore-keys: |
            ${{ runner.os }}-cache-python-pip-${{ hashFiles('**/requirements_build.txt') }}
            ${{ runner.os }}-cache-python-pip-


      - name: Nuitka Cache
        if: ${{ env.CACHE_NUITKA_GCC }}
        uses: actions/cache@v2
        with:
          path: ~\AppData\Local\Nuitka\Nuitka
          key: ${{ runner.os }}-cache-nuitka
          restore-keys: ${{ runner.os }}-cache-nuitka


      - name: Build Cache
        if: ${{ env.CACHE_BUILD }}
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}\Run.build
            ${{ github.workspace }}\Run.dist
            ${{ github.workspace }}\Run.onefile-build
          key: ${{ runner.os }}-cache-nuitka-build-${{ steps.genReleaseTimes.outputs.tag }}
          restore-keys: ${{ runner.os }}-cache-nuitka-build-


      - name: Setting Build Environment
        shell: pwsh
        run: |
          Write-Output "Copy & delete files"
          Move-Item ${{ github.workspace }}\Claset\Execution\${{ env.DEFAULT_MODULE_NAME }}\Run.py ${{ github.workspace }}\ -Verbose
          Move-Item ${{ github.workspace }}\Claset\Execution\${{ env.DEFAULT_MODULE_NAME }}\requirements_build.txt ${{ github.workspace }}\ -Verbose
          Get-ChildItem -Path ${{ github.workspace }}\Claset\Execution\ -Exclude ${{ env.DEFAULT_MODULE_NAME }} -Recurse -Directory | Remove-Item -Recurse -Force -Verbose


      - name: Setting Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: ${{ env.PYTHON_ARCHITECTURE }}


      - name: Setting PyPI Environment
        shell: pwsh
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements_build.txt


      - name: Using Develop Version Nuitka
        if: github.event.inputs.use_nuitka_develop_version
        shell: pwsh
        run: pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"


      - name: Show Environment
        shell: pwsh
        run: |
          python -c "from sys import version; print('Python', version)"
          Write-Output "PyPI packages list - All"
          Write-Output "==========================="
          pip list
          Write-Output "==========================="
          Write-Output ""
          Write-Output "PyPI packages list - Outdate"
          Write-Output "==========================="
          pip list --outdate
          Write-Output "==========================="


      - name: Build
        shell: pwsh
        run: python -m nuitka --standalone --onefile --follow-imports --assume-yes-for-downloads --include-data-dir=Translations=Translations --windows-product-name="Claset" --windows-file-version="1.0.0.0" --windows-product-version="0.1.0.147" --windows-company-name="Puqns_67" --windows-onefile-tempdir-spec="%TEMP%\Claset_%PID%_%TIME%" -o "${{ github.workspace }}\${{ steps.genFileName.outputs.filename }}" "${{ github.workspace }}\Run.py"


      - name: Upload Build Artifact to Actions
        if: ${{ env.UPLOAD_TO_ACTIONS }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.genFileName.outputs.filename }}
          path: ${{ github.workspace }}\${{ steps.genFileName.outputs.filename }}
          retention-days: ${{ env.RETENTION_DAYS }}



  Build_Ubuntu:
    name: Build_Ubuntu
    runs-on: ubuntu-latest
    needs: Build_Translations
    steps:
      - name: Checkout
        uses: actions/checkout@v2


      - name: Generate Times
        id: genReleaseTimes
        run: |
          echo "::set-output name=tag::$(date +'%Y/%m/%d_%H/%M/%S')"
          echo "::set-output name=filename::$(date +'%Y-%m-%d_%H-%M-%S')"


      - name: Generate release name
        id: genFileName
        run: |
          echo "::set-output name=filename::${{ env.RELEASES_NAME_PERFIX }}-${{ runner.os }}-${{ env.PYTHON_ARCHITECTURE }}-${{ steps.genReleaseTimes.outputs.filename }}"


      - name: PyPI Cache
        if: ${{ env.CACHE_PYPI }}
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-cache-python-pip-${{ hashFiles('**/requirements_build.txt') }}
          restore-keys: |
            ${{ runner.os }}-cache-python-pip-${{ hashFiles('**/requirements_build.txt') }}
            ${{ runner.os }}-cache-python-pip-


      - name: Nuitka Cache
        if: ${{ env.CACHE_NUITKA_GCC }}
        uses: actions/cache@v2
        with:
          path: ~/.local/share/Nuitka
          key: ${{ runner.os }}-cache-nuitka
          restore-keys: ${{ runner.os }}-cache-nuitka


      - name: Build Cache
        if: ${{ env.CACHE_BUILD }}
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/Run.build
            ${{ github.workspace }}/Run.dist
            ${{ github.workspace }}/Run.onefile-build
          key: ${{ runner.os }}-cache-nuitka-build-${{ steps.genReleaseTimes.outputs.tag }}
          restore-keys: ${{ runner.os }}-cache-nuitka-build-


      - name: Setting Build Environment
        shell: pwsh
        run: |
          Write-Output "Copy & delete files"
          Move-Item ${{ github.workspace }}/Claset/Execution/${{ env.DEFAULT_MODULE_NAME }}/Run.py ${{ github.workspace }}/ -Verbose
          Move-Item ${{ github.workspace }}/Claset/Execution/${{ env.DEFAULT_MODULE_NAME }}/requirements_build.txt ${{ github.workspace }}/ -Verbose
          Get-ChildItem -Path ${{ github.workspace }}/Claset/Execution/ -Exclude ${{ env.DEFAULT_MODULE_NAME }} -Recurse -Directory | Remove-Item -Recurse -Force -Verbose
          Write-Output "Install build tools"
          sudo apt-get install patchelf ccache


      - name: Setting Python Environment
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          architecture: ${{ env.PYTHON_ARCHITECTURE }}


      - name: Setting PyPI Environment
        shell: pwsh
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements_build.txt


      - name: Using Develop Version Nuitka
        if: github.event.inputs.use_nuitka_develop_version
        shell: pwsh
        run: pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"


      - name: Show Environment
        shell: pwsh
        run: |
          python -c "from sys import version; print('Python', version)"
          Write-Output "PyPI packages list - All"
          Write-Output "==========================="
          pip list
          Write-Output "==========================="
          Write-Output ""
          Write-Output "PyPI packages list - Outdate"
          Write-Output "==========================="
          pip list --outdate
          Write-Output "==========================="


      - name: Build
        shell: pwsh
        run: python -m nuitka --standalone --onefile --follow-imports --assume-yes-for-downloads --include-data-dir=Translations=Translations -o "${{ github.workspace }}/${{ steps.genFileName.outputs.filename }}" "${{ github.workspace }}/Run.py"


      - name: Upload Build Artifact to Actions
        if: ${{ env.UPLOAD_TO_ACTIONS }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ steps.genFileName.outputs.filename }}
          path: ${{ github.workspace }}/${{ steps.genFileName.outputs.filename }}
          retention-days: ${{ env.RETENTION_DAYS }}

